from PIL import Image
import math

#Leave blank to not convert text to image
#Must be a .txt file that exists
textinput = "input.txt" 
#Must have a valid .png filename
imgoutput = "output.png" 

#Leave blank to not convert image to text
#Must be an image that exists and is also generated by this algorithm
imginput = "" 

resize = 1

def text_to_image(text,imgoutput,resize = 15):
  pixels = []
  px = []
  for index, letter in enumerate(text):
    px.append(ord(letter))
    if (index+1)%3 == 0:
      pixels.append(tuple(px))
      px = []

  width = math.ceil(math.sqrt(len(text)/3))
  height = width
  img = Image.new("RGB", (width, height))

  for i, px in enumerate(pixels):
    y = int(i / (width))
    x = i % (width)
    img.putpixel((x, y), px)
  img = img.resize((width*resize, height*resize), Image.BOX)
  img.save(imgoutput)

def image_to_text(image, resize = 15):
  img = Image.open(image)
  img = img.resize((img.width//resize, img.height//resize), Image.BOX)
  width, height = img.size
  img_pixels = img.load()
  text = ""

  for i in range(int((width)**2)):
    x = i % (width)
    y = int(i / (width))
    for i in range(3):
      text+=chr(img_pixels[x,y][i])
  return text

if textinput!="":
  try:
    file = open(textinput,"r")
  except:
    print("You did not set a valid .txt file.  Check if the file you have set exists.")
  else:
    try:
      text_to_image(file.read(),imgoutput,resize)
      print("Your text has been converted, check " + imgoutput + " for the output image.")
    except:
      print("It looks like something went wrong with the text to image conversion process.")
if imginput!="":
  try:
    print(image_to_text(imginput,resize))
  except:
    print("You did not set a valid .png image. Check if the image you have set exists, or cannot be converted into text.")